CREATE TABLE  mockup(
	WMID CHAR(36) NOT NULL PRIMARY KEY,
	VersionID CHAR(36) NOT NULL PRIMARY KEY,
	WMName VARCHAR(50) NULL DEFAULT NULL ,
	RegisterDatetime DATETIME NULL DEFAULT NULL,
	CSSForHTMLWithID VARCHAR(max) NULL DEFAULT NULL ,
	HTMLWithID VARCHAR(max) NULL DEFAULT NULL ,
	UserID CHAR(36) NULL DEFAULT NULL PRIMARY KEY REFERENCES userTable(UserID)
	)